project:
  type: website

website:
  title: "Afonso Matoso Magalhães"
  site-url: https://afonsomm.github.io/data-science
  description: "My blog on Data Science"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/afonsomm
      - icon: rss
        href: index.xml
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



